FROM quay.io/redhat-appstudio-qe/build-e2e-epnv-tenant/build-suite-component-update-szpq/multi-component-parent-hzot@sha256:771ead97fc809381d98de291a2196e2fdd261274e8cd8aa1e13370a66f8061b6
RUN echo hello
