FROM quay.io/redhat-appstudio-qe/build-e2e-tpne-tenant/build-suite-component-update-ljxq/multi-component-parent-qttw@sha256:a9394f9b26f36ce042a530f2a5d320f6766faabe691750c4d1467e8d16ea6d83
RUN echo hello
